### ISSUE TITLE
making resume work...?

### ISSUE THREAD

**Issue by tischi** [embl-cba/ome-zarr-image-analysis-nextflow#8]
@BioinfoTongLI @krokicki 

It seems that [right now there is no new output](https://github.com/embl-cba/ome-zarr-image-analysis-nextflow/blob/e8d3917fa33b6db19f533a0b5ef5f737efa8cd94/main.nf#L20) into the work dir, correct?

Would that be an issue if we want to resume a workflow? That is, how would Nextflow know whether this process has sucessully finished?

Would it be an option to save the below version file _also_ in the work dir?
`cat <<-END_VERSIONS > ${omezarr_root}/${verion_file_name}`

Or maybe better: save it only into the work dir and then use the `publishDir` mechanism to copy it out into `${omezarr_root}`?

**Comment by BioinfoTongLI** [comment]
Hi @tischi, sorry I forgot to ping everybody.
I've moved the latest version to 
https://github.com/BioImageTools/ome-zarr-image-analysis-nextflow/tree/develop

Let's maybe default to that version.
And please checkout to `develop` branch for the latest version.

Regarding the issue here:
the problem with publishdir is that I am not sure if it can be dynamically set depending on input, e.g. meta, omezarr_root. 
From my previous experience, it didn't work for me
